name: starlineBot CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [12.22.9]
    steps:
      - uses: actions/checkout@v4
      - name: use node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run test